name: Auto replace CODEOWNERS group ID

on:
  push:
    branches:
      - main

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if target file changed
        id: check
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q ".github/workflows/codeowners-group-analysis.yaml"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Replace ID
        if: steps.check.outputs.changed == 'true'
        run: |
          FILE=".github/workflows/codeowners-group-analysis.yaml"

          if grep -q "C07G47JMQHM" "$FILE"; then
            sed -i 's/C07G47JMQHM/C09HT5VSXRB/g' "$FILE"
          else
            echo "Nothing to replace"
            exit 0
          fi

      - name: Create Pull Request
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-replace deprecated CODEOWNERS group ID"
          title: "Auto-replace deprecated CODEOWNERS group ID"
          body: |
            This PR was automatically generated to replace
            deprecated CODEOWNERS group ID.
          branch: auto/fix-codeowners-id
          base: main
